apiVersion: v1
kind: Pod
metadata:
  name: health-probe-pod
  namespace: test-app
spec:
  containers:
  - image: nginx:1.14.2
    name: liveness-readiness
    ports:
    - containerPort: 80
    readinessProbe:    # sprawdzanie czy pod jest gotowy do obslugi ruchu
      tcpSocket:
        port: 80
      initialDelaySeconds: 10   # czas do pierwszego sprawdzenia
      periodSeconds: 5          # co ile sekund sprawdzac
    livenessProbe:          # sprawdzanie czy pod jest "zywy", czy container dziala poprawnie, jesli nie to restartuje go
      tcpSocket:
        port: 80
      initialDelaySeconds: 15    # czas do pierwszego sprawdzenia
      periodSeconds: 20          # co ile sekund sprawdzac