apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jano-replicaset
  namespace: test-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: jano-app
  template:
    metadata:
      labels:
        app: jano-app
    spec:
      strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 25%          # ile dodatkowych podów może być utworzonych ponad zdefiniowaną liczbę replik
            maxUnavailable: 25%    # ile podów może być niedostępnych podczas aktualizacji
      containers:
      - name: jano-container
        image: nginx:1.24.0
        ports:
        - containerPort: 80   
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20