apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
  namespace: n8n
type: Opaque
stringData:
  N8N_ENCRYPTION_KEY: "wygeneruj_dlugi_losowy_klucz"
  POSTGRES_USER: "n8n"
  POSTGRES_PASSWORD: "TwojeHasloDB"
  POSTGRES_DB: "n8n"
