apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jfrog
spec:
  project: default
  source:
    repoURL: https://github.com/ja31582/k8s_cluster.git
    targetRevision: main
    path: helm-chart/jfrog
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: jfrog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
