apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cluster-access
  name: pod-reader
rules:
- apiGroups: [""]
  resources:
    - pods
    - pods/log
    - services
    - endpoints
    - persistentvolumeclaims
    - configmaps
    - secrets
    - events
    - namespaces
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]