apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: metallb-system
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
  # loadBalancerIP: 10.0.0.80   # opcjonalnie
