apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: test-lb-nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      LoadBalancerIP: 10.0.0.90

