
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jfrog-app
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.jfrog.io
      chart: artifactory
      targetRevision: 10.0.14
      helm:
        valueFiles:
          - $values/jfrog/values.yaml   # wskazanie na plik z drugiego źródła
    - repoURL: https://github.com/ja31582/k8s_cluster.git
      targetRevision: main
      ref: values                      # alias użyty powyżej w $values/...
      path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: jfrog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
