
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-artifactory-pvc
  namespace: jfrog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn   # zmień/usuń jeśli masz inny SC albo default
