apiVersion: apps/v1
kind: Deployment
metadata:
  name: interpod-affinity
  namespace: test-app
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
      nodeSelector:
        type: k8s-master
      tolerations:
      - effect: "NoSchedule"
        operator: "Exists"
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - etcd
            topologyKey: "kubernetes.io/hostname" #to moze byc rowniez "zone" lub "region"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nginx
            topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        kubernetes.io/hostname: k8s-master
