apiVersion: v1
kind: Pod
metadata:
  name: taint
  namespace: test-app
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    command :
      - /bin/sh
      - -c
      - |
        while true; do
          echo "Nginx is running"
          sleep 60
        done
  tolerations:
  - key: "key1"
    operator: "Equal"
    value: "value1"
    effect: "NoSchedule"
